server:
  port: 8000
spring:
  application:
    name: spring-security-v4
  datasource:
    url:
    username:
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

