server:
  port: 8000
spring:
  application:
    name: spring-security-v4
  sql:
    init:
      mode: always
  datasource:
    url:
    username:
    password: 
    data: classpath:data.sql
    initialization-mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
